### ISSUE TITLE
Cant find requireShippingAddress in ConsumerRequest

### ISSUE THREAD

**Issue by mathiso** [SwedbankPay/swedbank-pay-sdk-dotnet#383]
Hi,

I want to set requireShippingAddress to false, but it seems thats itś not included in ConsumerRequest?

**Comment by asbjornu** [comment]
Seems like you're correct. We warmly welcome pull requests if you're up for the challenge of adding it in yourself. 🙏🏼

**Comment by asbjornu** [comment]
Implemented in #384
